### PR TITLE
Homework 2.

### PR DESCRIPTION
**Pull request by mcmcgill**
This is Homework 2 for Max McGill.

### CODE REVIEW

**Comment by mcmcgill** [comment]
Dr. Settlage,

I attempted to use the table functions you mentioned and the project
options, but I couldn't get the functions to produce tables, and the
project options hid my outputs whenever I tried to include them. I'm not
sure where my mistake was, but I'd like to figure it out.
Also, the annotations were partially, if not mostly, for my own benefit.

Thanks!
Max McGill

**Comment by rsettlage** [comment]
OK, how about this:

Your code chuck has as header options echo=F.  That is ok, perhaps you can use include=T in addition.  Also, you can break the code up a bit more so that you can annotate it even more, i.e. do the importing in one code chunk with eval=T, cache=T, include=F and perhaps other options, then do the munging in another code chunk eval=T, cache=F while you are working on it, then in a final chunk for a particular problem, do eval=T, cache=F, include=T, results='asis' and in this one put the knit::kable or whatever table function you are using.  Ditto for plots.

And now you are seeing the power of git!!
Bob

**Comment by rsettlage** [comment]
I edited your .Rmd file, try doing a git pull in R and knitting that to see if you get a nicely formatted table.

Also, next time, put the homework in the homework directory...

**Comment by mcmcgill** [comment]
That sounds good, thanks!

**Pull request closed without merging**
