### PR TITLE
HW2_Walsh_Steve

### PR DESCRIPTION
**Pull request by stevewalsh124**
Hi Dr. Settlage, I will continue to work through the solutions you provided starting tomorrow and throughout the week. Thank you for the guidance.

### CODE REVIEW

**Comment by rsettlage** [comment]
OH, and ask me about the .gitignore file to get rid of other files you might not want in your repo

**Comment by stevewalsh124** [comment]
Thanks for the info and sorry for the late reply, I've been trying to mess with the .gitignore using lines such as:

*/02_data_munging_summarizing_R_git/hw2p5longjump.R
*/02_data_munging_summarizing_R_git/hw2p6plants.R
hw2p6plants.R
*/*.R

I have saved my .gitignore after each of these and updated my git window and the modified hw2p6plants.R is still in the window. My project and .gitignore file are in STAT_5014_homework, and those .R files are in a subdirectory 02_data_munging_summarizing_R_git

**Comment by rsettlage** [comment]
I think the problem is that you added the files to your repo before you altered the .gitignore.  I think you can do some command line magic, git rm <file> to remove them from tracking.

Also, btw, you are one of the few that was able to get new changes from the repo, so be prepared to answer questions…

**Comment by stevewalsh124** [comment]
I'm actually not sure what happened with that, in git I changed my directory to the forked repo, did the three commands (git remote add upstream, git checkout master, and git pull upstream master), but then it brought up a prompt where I had to type a message before I committed and I typed a message and tried hitting enter, ctrl+R, tab, etc and it wouldn't let me submit it. I ended up X'ing out of Git since I couldn't get it going. So it may have been from that, but it may have been from refreshing the file listing within RStudio after forking/cloning.

**Comment by rsettlage** [comment]
Ah, sorry for that.  It put you in a vim editor, so next time, hit <esc>, the colon ":", and then type wc.  All obvious commands.  LOL

I think on the last one, git pull upstream master, you could have added a -m "getting upstream changes" flag to get that done.

**Pull request closed without merging**
