### PR TITLE
HW2_Yun_Young

### PR DESCRIPTION
**Pull request by yyun1**
I completed up to #6, but had difficulty in #7 as R kept crashing because of large volume of data.  It was especially confusing because fread() and read.csv() functions only work for some of the files. For me,
fread() function did not work on "Personenauto_basisdata.csv" file and returned an error. So I tried read.csv() function, but it just crashes R after tremendous loading time. I also tried to use read.csv() on other files to read data, but it did not work. I will continue to make changes to try to get it working.

### CODE REVIEW

**Comment by rsettlage** [comment]
Hi,
can you push and submit the pdf as well?
Thanks,
Bob

**Comment by yyun1** [comment]
I think there was an error in downloading the Car_Person file. I will submit again after re-try.

Young Yun

**Comment by rsettlage** [comment]
Don't worry about #7 if you don't have time, we will discuss tomorrow.  If you could push the .pdf, that would be great.

**Comment by rsettlage** [comment]
What platform are you on?  PC?  OS?  RAM?

**Comment by yyun1** [comment]
I am using PC.

**Pull request closed without merging**
